# Generated by Django 5.2.6 on 2025-11-05 16:52

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='membership_id',
            field=models.UUIDField(default=uuid.uuid1, editable=False),
        ),
    ]
