# Generated by Django 5.2.6 on 2025-11-05 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0002_alter_customers_membership_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventoryreceived',
            name='quantity_received',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='stock_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
