# Generated by Django 5.2.6 on 2025-11-11 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0004_alter_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('topic', models.CharField(max_length=32, unique=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('fan_gpio', models.IntegerField(default=18)),
                ('fan_on', models.BooleanField(default=False)),
                ('alert_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('last_alert_ts', models.DateTimeField(blank=True, null=True)),
                ('temp_threshold', models.FloatField(default=8.0)),
                ('humidity_threshold', models.FloatField(default=85.0)),
            ],
        ),
    ]
