# Generated by Django 5.2.7 on 2025-12-01 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0005_fridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fan_gpio',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='fridge',
            name='last_alert_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='humidity_threshold',
            field=models.FloatField(default=51.0),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='name',
            field=models.CharField(max_length=32, unique=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='temp_threshold',
            field=models.FloatField(default=21.0),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='temperature',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='topic',
            field=models.CharField(max_length=32, unique=True),
        ),
    ]
