# Generated by Django 5.2.6 on 2025-11-10 16:07

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0004_fridge_alert_email_fridge_fan_gpio_fridge_fan_on_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$')])),
                ('password', models.CharField()),
                ('membership_id', models.UUIDField(default=uuid.uuid1, editable=False)),
                ('points', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('price', models.FloatField()),
                ('epc', models.CharField(max_length=50, unique=True)),
                ('upc', models.CharField(max_length=50, unique=True)),
                ('producer_company', models.CharField(max_length=100)),
                ('image_url', models.CharField()),
                ('stock_quantity', models.IntegerField(default=0)),
                ('expiry_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='InventoryReceived',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_received', models.DateField()),
                ('quantity_received', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartstore.products')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('points_earned', models.IntegerField(default=0)),
                ('total_price', models.IntegerField()),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartstore.customers')),
            ],
        ),
        migrations.CreateModel(
            name='Receipts_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartstore.products')),
                ('receipt_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='smartstore.receipts')),
            ],
            options={
                'db_table': 'receipts_products',
                'unique_together': {('receipt_id', 'product_id')},
            },
        ),
    ]
