# Generated by Django 5.2.7 on 2025-10-26 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
                ('topic', models.CharField(max_length=32, unique=True)),
                ('temperature', models.FloatField(blank=True, null=True)),
                ('humidity', models.FloatField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('temp_threshold', models.FloatField(default=5.0)),
            ],
        ),
    ]
