# Generated by Django 5.2.7 on 2025-10-27 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0002_fridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='humidity_threshold',
            field=models.FloatField(default=85.0),
        ),
        migrations.AlterField(
            model_name='fridge',
            name='temp_threshold',
            field=models.FloatField(default=8.0),
        ),
    ]
