# Generated by Django 5.2.7 on 2025-10-27 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smartstore', '0003_fridge_humidity_threshold_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fridge',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fan_gpio',
            field=models.IntegerField(default=18),
        ),
        migrations.AddField(
            model_name='fridge',
            name='fan_on',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='fridge',
            name='last_alert_ts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
