# Generated by Django 5.2.6 on 2025-11-05 20:40

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0003_inventoryreceived_quantity_received_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, unique=True, validators=[django.core.validators.RegexValidator(regex='^\\d{9,15}$')]),
        ),
        migrations.AlterField(
            model_name='inventoryreceived',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase3.products'),
        ),
        migrations.AlterField(
            model_name='receipts',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase3.customers'),
        ),
        migrations.AlterField(
            model_name='receipts_products',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase3.products'),
        ),
        migrations.AlterField(
            model_name='receipts_products',
            name='receipt_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='phase3.receipts'),
        ),
    ]
