# Generated by Django 5.2.7 on 2025-11-24 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phase3', '0004_alter_customers_phone_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fridge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('topic', models.CharField(max_length=100)),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('temp_threshold', models.FloatField(default=0)),
                ('humidity_threshold', models.FloatField(default=0)),
                ('fan_on', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
